   // Element data
        const elements = [
            // Period 1
            { number: 1, symbol: "H", name: "Hydrogen", nameVi: "Hiđrô", mass: 1.008, category: "nonmetal", period: 1, group: 1, electronegativity: 2.20, state: "Khí", year: "1766", config: "1s¹", fact: "Nguyên tố phổ biến nhất trong vũ trụ, chiếm 75% khối lượng vật chất thông thường." },
            { number: 2, symbol: "He", name: "Helium", nameVi: "Heli", mass: 4.003, category: "noble", period: 1, group: 18, electronegativity: null, state: "Khí", year: "1868", config: "1s²", fact: "Khí nhẹ thứ hai, được dùng cho khinh khí cầu và làm mát thiết bị siêu dẫn." },

            // Period 2
            { number: 3, symbol: "Li", name: "Lithium", nameVi: "Liti", mass: 6.941, category: "alkali", period: 2, group: 1, electronegativity: 0.98, state: "Rắn", year: "1817", config: "[He] 2s¹", fact: "Kim loại nhẹ nhất, được sử dụng rộng rãi trong pin lithium-ion." },
            { number: 4, symbol: "Be", name: "Beryllium", nameVi: "Berili", mass: 9.012, category: "alkaline", period: 2, group: 2, electronegativity: 1.57, state: "Rắn", year: "1798", config: "[He] 2s²", fact: "Kim loại cứng, nhẹ, được dùng trong hợp kim hàng không vũ trụ." },
            { number: 5, symbol: "B", name: "Boron", nameVi: "Bo", mass: 10.81, category: "metalloid", period: 2, group: 13, electronegativity: 2.04, state: "Rắn", year: "1808", config: "[He] 2s² 2p¹", fact: "Á kim quan trọng trong sản xuất thủy tinh borosilicate (Pyrex)." },
            { number: 6, symbol: "C", name: "Carbon", nameVi: "Cacbon", mass: 12.01, category: "nonmetal", period: 2, group: 14, electronegativity: 2.55, state: "Rắn", year: "Cổ đại", config: "[He] 2s² 2p²", fact: "Cơ sở của sự sống, có thể tồn tại dưới nhiều dạng thù hình như kim cương, than chì." },
            { number: 7, symbol: "N", name: "Nitrogen", nameVi: "Nitơ", mass: 14.01, category: "nonmetal", period: 2, group: 15, electronegativity: 3.04, state: "Khí", year: "1772", config: "[He] 2s² 2p³", fact: "Chiếm 78% khí quyển Trái Đất, cần thiết cho protein và DNA." },
            { number: 8, symbol: "O", name: "Oxygen", nameVi: "Oxi", mass: 16.00, category: "nonmetal", period: 2, group: 16, electronegativity: 3.44, state: "Khí", year: "1774", config: "[He] 2s² 2p⁴", fact: "Nguyên tố thiết yếu cho hô hấp, chiếm 21% khí quyển Trái Đất." },
            { number: 9, symbol: "F", name: "Fluorine", nameVi: "Flo", mass: 19.00, category: "halogen", period: 2, group: 17, electronegativity: 3.98, state: "Khí", year: "1886", config: "[He] 2s² 2p⁵", fact: "Nguyên tố có độ âm điện cao nhất, dùng trong kem đánh răng." },
            { number: 10, symbol: "Ne", name: "Neon", nameVi: "Neon", mass: 20.18, category: "noble", period: 2, group: 18, electronegativity: null, state: "Khí", year: "1898", config: "[He] 2s² 2p⁶", fact: "Tạo ra ánh sáng đỏ-cam đặc trưng trong đèn neon." },

            // Period 3
            { number: 11, symbol: "Na", name: "Sodium", nameVi: "Natri", mass: 22.99, category: "alkali", period: 3, group: 1, electronegativity: 0.93, state: "Rắn", year: "1807", config: "[Ne] 3s¹", fact: "Kim loại mềm, phản ứng mạnh với nước, thành phần của muối ăn." },
            { number: 12, symbol: "Mg", name: "Magnesium", nameVi: "Magiê", mass: 24.31, category: "alkaline", period: 3, group: 2, electronegativity: 1.31, state: "Rắn", year: "1755", config: "[Ne] 3s²", fact: "Kim loại nhẹ, được dùng trong pháo hoa và hợp kim máy bay." },
            { number: 13, symbol: "Al", name: "Aluminium", nameVi: "Nhôm", mass: 26.98, category: "post-transition", period: 3, group: 13, electronegativity: 1.61, state: "Rắn", year: "1825", config: "[Ne] 3s² 3p¹", fact: "Kim loại phổ biến nhất trong vỏ Trái Đất, dùng làm lon nước ngọt." },
            { number: 14, symbol: "Si", name: "Silicon", nameVi: "Silic", mass: 28.09, category: "metalloid", period: 3, group: 14, electronegativity: 1.90, state: "Rắn", year: "1824", config: "[Ne] 3s² 3p²", fact: "Nguyên liệu chính cho chip máy tính và pin mặt trời." },
            { number: 15, symbol: "P", name: "Phosphorus", nameVi: "Photpho", mass: 30.97, category: "nonmetal", period: 3, group: 15, electronegativity: 2.19, state: "Rắn", year: "1669", config: "[Ne] 3s² 3p³", fact: "Cần thiết cho DNA và ATP, được dùng trong diêm và pháo hoa." },
            { number: 16, symbol: "S", name: "Sulfur", nameVi: "Lưu huỳnh", mass: 32.07, category: "nonmetal", period: 3, group: 16, electronegativity: 2.58, state: "Rắn", year: "Cổ đại", config: "[Ne] 3s² 3p⁴", fact: "Có mùi đặc trưng (mùi trứng thối), dùng sản xuất axit sunfuric." },
            { number: 17, symbol: "Cl", name: "Chlorine", nameVi: "Clo", mass: 35.45, category: "halogen", period: 3, group: 17, electronegativity: 3.16, state: "Khí", year: "1774", config: "[Ne] 3s² 3p⁵", fact: "Dùng khử trùng nước uống và hồ bơi." },
            { number: 18, symbol: "Ar", name: "Argon", nameVi: "Argon", mass: 39.95, category: "noble", period: 3, group: 18, electronegativity: null, state: "Khí", year: "1894", config: "[Ne] 3s² 3p⁶", fact: "Khí trơ phổ biến nhất, dùng trong bóng đèn và hàn." },

            // Period 4
            { number: 19, symbol: "K", name: "Potassium", nameVi: "Kali", mass: 39.10, category: "alkali", period: 4, group: 1, electronegativity: 0.82, state: "Rắn", year: "1807", config: "[Ar] 4s¹", fact: "Cần thiết cho hoạt động cơ và thần kinh, có trong chuối." },
            { number: 20, symbol: "Ca", name: "Calcium", nameVi: "Canxi", mass: 40.08, category: "alkaline", period: 4, group: 2, electronegativity: 1.00, state: "Rắn", year: "1808", config: "[Ar] 4s²", fact: "Thành phần chính của xương và răng, có nhiều trong sữa." },
            { number: 21, symbol: "Sc", name: "Scandium", nameVi: "Scandi", mass: 44.96, category: "transition", period: 4, group: 3, electronegativity: 1.36, state: "Rắn", year: "1879", config: "[Ar] 3d¹ 4s²", fact: "Kim loại chuyển tiếp đầu tiên, dùng trong đèn hồ quang." },
            { number: 22, symbol: "Ti", name: "Titanium", nameVi: "Titan", mass: 47.87, category: "transition", period: 4, group: 4, electronegativity: 1.54, state: "Rắn", year: "1791", config: "[Ar] 3d² 4s²", fact: "Kim loại nhẹ, bền, dùng trong máy bay và cấy ghép y tế." },
            { number: 23, symbol: "V", name: "Vanadium", nameVi: "Vanadi", mass: 50.94, category: "transition", period: 4, group: 5, electronegativity: 1.63, state: "Rắn", year: "1801", config: "[Ar] 3d³ 4s²", fact: "Làm thép cứng hơn, dùng trong lò xo và công cụ." },
            { number: 24, symbol: "Cr", name: "Chromium", nameVi: "Crom", mass: 52.00, category: "transition", period: 4, group: 6, electronegativity: 1.66, state: "Rắn", year: "1797", config: "[Ar] 3d⁵ 4s¹", fact: "Cho màu sáng bóng đặc trưng, dùng mạ kim loại." },
            { number: 25, symbol: "Mn", name: "Manganese", nameVi: "Mangan", mass: 54.94, category: "transition", period: 4, group: 7, electronegativity: 1.55, state: "Rắn", year: "1774", config: "[Ar] 3d⁵ 4s²", fact: "Dùng trong sản xuất thép và pin khô." },
            { number: 26, symbol: "Fe", name: "Iron", nameVi: "Sắt", mass: 55.85, category: "transition", period: 4, group: 8, electronegativity: 1.83, state: "Rắn", year: "Cổ đại", config: "[Ar] 3d⁶ 4s²", fact: "Kim loại được sử dụng nhiều nhất, cần thiết cho hemoglobin máu." },
            { number: 27, symbol: "Co", name: "Cobalt", nameVi: "Coban", mass: 58.93, category: "transition", period: 4, group: 9, electronegativity: 1.88, state: "Rắn", year: "1735", config: "[Ar] 3d⁷ 4s²", fact: "Tạo màu xanh đặc trưng, dùng trong pin lithium-ion." },
            { number: 28, symbol: "Ni", name: "Nickel", nameVi: "Niken", mass: 58.69, category: "transition", period: 4, group: 10, electronegativity: 1.91, state: "Rắn", year: "1751", config: "[Ar] 3d⁸ 4s²", fact: "Dùng trong tiền xu và thép không gỉ." },
            { number: 29, symbol: "Cu", name: "Copper", nameVi: "Đồng", mass: 63.55, category: "transition", period: 4, group: 11, electronegativity: 1.90, state: "Rắn", year: "Cổ đại", config: "[Ar] 3d¹⁰ 4s¹", fact: "Dẫn điện tốt thứ hai sau bạc, dùng trong dây điện." },
            { number: 30, symbol: "Zn", name: "Zinc", nameVi: "Kẽm", mass: 65.38, category: "transition", period: 4, group: 12, electronegativity: 1.65, state: "Rắn", year: "Cổ đại", config: "[Ar] 3d¹⁰ 4s²", fact: "Bảo vệ sắt khỏi gỉ, quan trọng cho hệ miễn dịch." },
            { number: 31, symbol: "Ga", name: "Gallium", nameVi: "Gali", mass: 69.72, category: "post-transition", period: 4, group: 13, electronegativity: 1.81, state: "Rắn", year: "1875", config: "[Ar] 3d¹⁰ 4s² 4p¹", fact: "Nóng chảy trong lòng bàn tay, dùng trong LED." },
            { number: 32, symbol: "Ge", name: "Germanium", nameVi: "Gecmani", mass: 72.63, category: "metalloid", period: 4, group: 14, electronegativity: 2.01, state: "Rắn", year: "1886", config: "[Ar] 3d¹⁰ 4s² 4p²", fact: "Chất bán dẫn quan trọng trong điện tử học." },
            { number: 33, symbol: "As", name: "Arsenic", nameVi: "Asen", mass: 74.92, category: "metalloid", period: 4, group: 15, electronegativity: 2.18, state: "Rắn", year: "Cổ đại", config: "[Ar] 3d¹⁰ 4s² 4p³", fact: "Chất độc nổi tiếng trong lịch sử, dùng trong bảo quản gỗ." },
            { number: 34, symbol: "Se", name: "Selenium", nameVi: "Selen", mass: 78.97, category: "nonmetal", period: 4, group: 16, electronegativity: 2.55, state: "Rắn", year: "1817", config: "[Ar] 3d¹⁰ 4s² 4p⁴", fact: "Vi lượng cần thiết cho cơ thể, dùng trong dầu gội trị gàu." },
            { number: 35, symbol: "Br", name: "Bromine", nameVi: "Brom", mass: 79.90, category: "halogen", period: 4, group: 17, electronegativity: 2.96, state: "Lỏng", year: "1826", config: "[Ar] 3d¹⁰ 4s² 4p⁵", fact: "Một trong hai nguyên tố lỏng ở nhiệt độ phòng." },
            { number: 36, symbol: "Kr", name: "Krypton", nameVi: "Kripton", mass: 83.80, category: "noble", period: 4, group: 18, electronegativity: 3.00, state: "Khí", year: "1898", config: "[Ar] 3d¹⁰ 4s² 4p⁶", fact: "Không liên quan đến kryptonite của Superman!" },

            // Period 5
            { number: 37, symbol: "Rb", name: "Rubidium", nameVi: "Rubidi", mass: 85.47, category: "alkali", period: 5, group: 1, electronegativity: 0.82, state: "Rắn", year: "1861", config: "[Kr] 5s¹", fact: "Dùng trong đồng hồ nguyên tử và pháo hoa màu tím." },
            { number: 38, symbol: "Sr", name: "Strontium", nameVi: "Stronti", mass: 87.62, category: "alkaline", period: 5, group: 2, electronegativity: 0.95, state: "Rắn", year: "1790", config: "[Kr] 5s²", fact: "Tạo màu đỏ trong pháo hoa." },
            { number: 39, symbol: "Y", name: "Yttrium", nameVi: "Ytri", mass: 88.91, category: "transition", period: 5, group: 3, electronegativity: 1.22, state: "Rắn", year: "1794", config: "[Kr] 4d¹ 5s²", fact: "Dùng trong TV màu và LED trắng." },
            { number: 40, symbol: "Zr", name: "Zirconium", nameVi: "Zirconi", mass: 91.22, category: "transition", period: 5, group: 4, electronegativity: 1.33, state: "Rắn", year: "1789", config: "[Kr] 4d² 5s²", fact: "Dùng trong lò phản ứng hạt nhân và đá quý nhân tạo." },
            { number: 41, symbol: "Nb", name: "Niobium", nameVi: "Niobi", mass: 92.91, category: "transition", period: 5, group: 5, electronegativity: 1.6, state: "Rắn", year: "1801", config: "[Kr] 4d⁴ 5s¹", fact: "Dùng trong hợp kim siêu dẫn và trang sức." },
            { number: 42, symbol: "Mo", name: "Molybdenum", nameVi: "Molypđen", mass: 95.95, category: "transition", period: 5, group: 6, electronegativity: 2.16, state: "Rắn", year: "1781", config: "[Kr] 4d⁵ 5s¹", fact: "Làm thép cứng và bền nhiệt, cần thiết cho enzyme." },
            { number: 43, symbol: "Tc", name: "Technetium", nameVi: "Tecneti", mass: 98, category: "transition", period: 5, group: 7, electronegativity: 1.9, state: "Rắn", year: "1937", config: "[Kr] 4d⁵ 5s²", fact: "Nguyên tố đầu tiên được tổng hợp nhân tạo." },
            { number: 44, symbol: "Ru", name: "Ruthenium", nameVi: "Ruteni", mass: 101.1, category: "transition", period: 5, group: 8, electronegativity: 2.2, state: "Rắn", year: "1844", config: "[Kr] 4d⁷ 5s¹", fact: "Kim loại quý hiếm, dùng trong đầu bút máy cao cấp." },
            { number: 45, symbol: "Rh", name: "Rhodium", nameVi: "Rođi", mass: 102.9, category: "transition", period: 5, group: 9, electronegativity: 2.28, state: "Rắn", year: "1803", config: "[Kr] 4d⁸ 5s¹", fact: "Kim loại đắt nhất thế giới, dùng trong bộ chuyển đổi xúc tác ô tô." },
            { number: 46, symbol: "Pd", name: "Palladium", nameVi: "Palađi", mass: 106.4, category: "transition", period: 5, group: 10, electronegativity: 2.20, state: "Rắn", year: "1803", config: "[Kr] 4d¹⁰", fact: "Hấp thụ hydro gấp 900 lần thể tích, dùng trong xúc tác ô tô." },
            { number: 47, symbol: "Ag", name: "Silver", nameVi: "Bạc", mass: 107.9, category: "transition", period: 5, group: 11, electronegativity: 1.93, state: "Rắn", year: "Cổ đại", config: "[Kr] 4d¹⁰ 5s¹", fact: "Dẫn điện tốt nhất, có tính kháng khuẩn tự nhiên." },
            { number: 48, symbol: "Cd", name: "Cadmium", nameVi: "Cađimi", mass: 112.4, category: "transition", period: 5, group: 12, electronegativity: 1.69, state: "Rắn", year: "1817", config: "[Kr] 4d¹⁰ 5s²", fact: "Dùng trong pin NiCd, độc hại với môi trường." },
            { number: 49, symbol: "In", name: "Indium", nameVi: "Inđi", mass: 114.8, category: "post-transition", period: 5, group: 13, electronegativity: 1.78, state: "Rắn", year: "1863", config: "[Kr] 4d¹⁰ 5s² 5p¹", fact: "Dùng trong màn hình cảm ứng và TV phẳng." },
            { number: 50, symbol: "Sn", name: "Tin", nameVi: "Thiếc", mass: 118.7, category: "post-transition", period: 5, group: 14, electronegativity: 1.96, state: "Rắn", year: "Cổ đại", config: "[Kr] 4d¹⁰ 5s² 5p²", fact: "Dùng làm hộp đựng thực phẩm và hàn điện tử." },
            { number: 51, symbol: "Sb", name: "Antimony", nameVi: "Antimon", mass: 121.8, category: "metalloid", period: 5, group: 15, electronegativity: 2.05, state: "Rắn", year: "Cổ đại", config: "[Kr] 4d¹⁰ 5s² 5p³", fact: "Làm chì trong pin acid và chống cháy." },
            { number: 52, symbol: "Te", name: "Tellurium", nameVi: "Telu", mass: 127.6, category: "metalloid", period: 5, group: 16, electronegativity: 2.1, state: "Rắn", year: "1783", config: "[Kr] 4d¹⁰ 5s² 5p⁴", fact: "Dùng trong đĩa DVD-RW và pin mặt trời." },
            { number: 53, symbol: "I", name: "Iodine", nameVi: "Iot", mass: 126.9, category: "halogen", period: 5, group: 17, electronegativity: 2.66, state: "Rắn", year: "1811", config: "[Kr] 4d¹⁰ 5s² 5p⁵", fact: "Cần thiết cho tuyến giáp, dùng sát trùng vết thương." },
            { number: 54, symbol: "Xe", name: "Xenon", nameVi: "Xenon", mass: 131.3, category: "noble", period: 5, group: 18, electronegativity: 2.60, state: "Khí", year: "1898", config: "[Kr] 4d¹⁰ 5s² 5p⁶", fact: "Dùng trong đèn pha ô tô và gây mê trong y tế." },

            // Period 6
            { number: 55, symbol: "Cs", name: "Cesium", nameVi: "Xesi", mass: 132.9, category: "alkali", period: 6, group: 1, electronegativity: 0.79, state: "Rắn", year: "1860", config: "[Xe] 6s¹", fact: "Kim loại có độ âm điện thấp nhất, dùng trong đồng hồ nguyên tử." },
            { number: 56, symbol: "Ba", name: "Barium", nameVi: "Bari", mass: 137.3, category: "alkaline", period: 6, group: 2, electronegativity: 0.89, state: "Rắn", year: "1808", config: "[Xe] 6s²", fact: "Tạo màu xanh lá trong pháo hoa, dùng chụp X-quang đường tiêu hóa." },
            // Lanthanides placeholder
            { number: 57, symbol: "La", name: "Lanthanum", nameVi: "Lantan", mass: 138.9, category: "lanthanide", period: 6, group: 3, electronegativity: 1.10, state: "Rắn", year: "1839", config: "[Xe] 5d¹ 6s²", fact: "Dùng trong pin hybrid và thấu kính máy ảnh." },
            { number: 72, symbol: "Hf", name: "Hafnium", nameVi: "Hafni", mass: 178.5, category: "transition", period: 6, group: 4, electronegativity: 1.3, state: "Rắn", year: "1923", config: "[Xe] 4f¹⁴ 5d² 6s²", fact: "Dùng trong thanh điều khiển lò phản ứng hạt nhân." },
            { number: 73, symbol: "Ta", name: "Tantalum", nameVi: "Tantan", mass: 180.9, category: "transition", period: 6, group: 5, electronegativity: 1.5, state: "Rắn", year: "1802", config: "[Xe] 4f¹⁴ 5d³ 6s²", fact: "Dùng trong tụ điện điện thoại và cấy ghép y tế." },
            { number: 74, symbol: "W", name: "Tungsten", nameVi: "Vonfram", mass: 183.8, category: "transition", period: 6, group: 6, electronegativity: 2.36, state: "Rắn", year: "1783", config: "[Xe] 4f¹⁴ 5d⁴ 6s²", fact: "Kim loại có nhiệt độ nóng chảy cao nhất (3422°C)." },
            { number: 75, symbol: "Re", name: "Rhenium", nameVi: "Reni", mass: 186.2, category: "transition", period: 6, group: 7, electronegativity: 1.9, state: "Rắn", year: "1925", config: "[Xe] 4f¹⁴ 5d⁵ 6s²", fact: "Nguyên tố hiếm, dùng trong động cơ phản lực." },
            { number: 76, symbol: "Os", name: "Osmium", nameVi: "Osmi", mass: 190.2, category: "transition", period: 6, group: 8, electronegativity: 2.2, state: "Rắn", year: "1803", config: "[Xe] 4f¹⁴ 5d⁶ 6s²", fact: "Nguyên tố có mật độ cao nhất trong các nguyên tố." },
            { number: 77, symbol: "Ir", name: "Iridium", nameVi: "Iriđi", mass: 192.2, category: "transition", period: 6, group: 9, electronegativity: 2.20, state: "Rắn", year: "1803", config: "[Xe] 4f¹⁴ 5d⁷ 6s²", fact: "Kim loại chống ăn mòn tốt nhất, dùng trong bugi cao cấp." },
            { number: 78, symbol: "Pt", name: "Platinum", nameVi: "Platin", mass: 195.1, category: "transition", period: 6, group: 10, electronegativity: 2.28, state: "Rắn", year: "1735", config: "[Xe] 4f¹⁴ 5d⁹ 6s¹", fact: "Kim loại quý, dùng trong trang sức và xúc tác ô tô." },
            { number: 79, symbol: "Au", name: "Gold", nameVi: "Vàng", mass: 197.0, category: "transition", period: 6, group: 11, electronegativity: 2.54, state: "Rắn", year: "Cổ đại", config: "[Xe] 4f¹⁴ 5d¹⁰ 6s¹", fact: "Kim loại quý được ưa chuộng nhất, không bị oxy hóa trong không khí." },
            { number: 80, symbol: "Hg", name: "Mercury", nameVi: "Thủy ngân", mass: 200.6, category: "transition", period: 6, group: 12, electronegativity: 2.00, state: "Lỏng", year: "Cổ đại", config: "[Xe] 4f¹⁴ 5d¹⁰ 6s²", fact: "Kim loại lỏng duy nhất ở nhiệt độ phòng." },
            { number: 81, symbol: "Tl", name: "Thallium", nameVi: "Tali", mass: 204.4, category: "post-transition", period: 6, group: 13, electronegativity: 1.62, state: "Rắn", year: "1861", config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹", fact: "Rất độc, từng được dùng làm thuốc diệt chuột." },
            { number: 82, symbol: "Pb", name: "Lead", nameVi: "Chì", mass: 207.2, category: "post-transition", period: 6, group: 14, electronegativity: 1.87, state: "Rắn", year: "Cổ đại", config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²", fact: "Từng dùng trong xăng và sơn, nay hạn chế vì độc hại." },
            { number: 83, symbol: "Bi", name: "Bismuth", nameVi: "Bitmut", mass: 209.0, category: "post-transition", period: 6, group: 15, electronegativity: 2.02, state: "Rắn", year: "1753", config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³", fact: "Tạo tinh thể cầu vồng đẹp, dùng trong thuốc dạ dày." },
            { number: 84, symbol: "Po", name: "Polonium", nameVi: "Poloni", mass: 209, category: "metalloid", period: 6, group: 16, electronegativity: 2.0, state: "Rắn", year: "1898", config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴", fact: "Phóng xạ mạnh, được Marie Curie phát hiện." },
            { number: 85, symbol: "At", name: "Astatine", nameVi: "Atatin", mass: 210, category: "halogen", period: 6, group: 17, electronegativity: 2.2, state: "Rắn", year: "1940", config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵", fact: "Nguyên tố tự nhiên hiếm nhất trên Trái Đất." },
            { number: 86, symbol: "Rn", name: "Radon", nameVi: "Rađon", mass: 222, category: "noble", period: 6, group: 18, electronegativity: 2.2, state: "Khí", year: "1900", config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶", fact: "Khí phóng xạ, có thể tích tụ trong tầng hầm nhà." },

            // Period 7
            { number: 87, symbol: "Fr", name: "Francium", nameVi: "Franxi", mass: 223, category: "alkali", period: 7, group: 1, electronegativity: 0.7, state: "Rắn", year: "1939", config: "[Rn] 7s¹", fact: "Kim loại hoạt động mạnh nhất, cực kỳ hiếm và phóng xạ." },
            { number: 88, symbol: "Ra", name: "Radium", nameVi: "Rađi", mass: 226, category: "alkaline", period: 7, group: 2, electronegativity: 0.9, state: "Rắn", year: "1898", config: "[Rn] 7s²", fact: "Phát sáng trong bóng tối, từng dùng trong đồng hồ dạ quang." },
            { number: 89, symbol: "Ac", name: "Actinium", nameVi: "Actini", mass: 227, category: "actinide", period: 7, group: 3, electronegativity: 1.1, state: "Rắn", year: "1899", config: "[Rn] 6d¹ 7s²", fact: "Nguyên tố đầu tiên của họ actinide, phát sáng xanh nhạt." },
            { number: 104, symbol: "Rf", name: "Rutherfordium", nameVi: "Rutherforđi", mass: 267, category: "transition", period: 7, group: 4, electronegativity: null, state: "Rắn", year: "1969", config: "[Rn] 5f¹⁴ 6d² 7s²", fact: "Đặt theo tên Ernest Rutherford, cha đẻ vật lý hạt nhân." },
            { number: 105, symbol: "Db", name: "Dubnium", nameVi: "Dubni", mass: 268, category: "transition", period: 7, group: 5, electronegativity: null, state: "Rắn", year: "1970", config: "[Rn] 5f¹⁴ 6d³ 7s²", fact: "Đặt theo tên thành phố Dubna, Nga." },
            { number: 106, symbol: "Sg", name: "Seaborgium", nameVi: "Seaborgi", mass: 269, category: "transition", period: 7, group: 6, electronegativity: null, state: "Rắn", year: "1974", config: "[Rn] 5f¹⁴ 6d⁴ 7s²", fact: "Đặt theo tên Glenn Seaborg khi ông còn sống." },
            { number: 107, symbol: "Bh", name: "Bohrium", nameVi: "Bohri", mass: 270, category: "transition", period: 7, group: 7, electronegativity: null, state: "Rắn", year: "1981", config: "[Rn] 5f¹⁴ 6d⁵ 7s²", fact: "Đặt theo tên Niels Bohr, cha đẻ cơ học lượng tử." },
            { number: 108, symbol: "Hs", name: "Hassium", nameVi: "Hassi", mass: 277, category: "transition", period: 7, group: 8, electronegativity: null, state: "Rắn", year: "1984", config: "[Rn] 5f¹⁴ 6d⁶ 7s²", fact: "Đặt theo tên tiểu bang Hesse, Đức." },
            { number: 109, symbol: "Mt", name: "Meitnerium", nameVi: "Meitneri", mass: 278, category: "unknown", period: 7, group: 9, electronegativity: null, state: "Rắn", year: "1982", config: "[Rn] 5f¹⁴ 6d⁷ 7s²", fact: "Đặt theo tên Lise Meitner, người đồng phát hiện phân hạch." },
            { number: 110, symbol: "Ds", name: "Darmstadtium", nameVi: "Darmstadti", mass: 281, category: "unknown", period: 7, group: 10, electronegativity: null, state: "Rắn", year: "1994", config: "[Rn] 5f¹⁴ 6d⁸ 7s²", fact: "Đặt theo tên thành phố Darmstadt, Đức." },
            { number: 111, symbol: "Rg", name: "Roentgenium", nameVi: "Roentgeni", mass: 282, category: "unknown", period: 7, group: 11, electronegativity: null, state: "Rắn", year: "1994", config: "[Rn] 5f¹⁴ 6d⁹ 7s²", fact: "Đặt theo tên Wilhelm Röntgen, người phát hiện tia X." },
            { number: 112, symbol: "Cn", name: "Copernicium", nameVi: "Copernici", mass: 285, category: "unknown", period: 7, group: 12, electronegativity: null, state: "Khí?", year: "1996", config: "[Rn] 5f¹⁴ 6d¹⁰ 7s²", fact: "Đặt theo tên Nicolaus Copernicus." },
            { number: 113, symbol: "Nh", name: "Nihonium", nameVi: "Nihoni", mass: 286, category: "unknown", period: 7, group: 13, electronegativity: null, state: "Rắn", year: "2004", config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹", fact: "Nguyên tố đầu tiên được đặt tên bởi châu Á (Nhật Bản)." },
            { number: 114, symbol: "Fl", name: "Flerovium", nameVi: "Flerovi", mass: 289, category: "unknown", period: 7, group: 14, electronegativity: null, state: "Rắn", year: "1998", config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²", fact: "Đặt theo tên Georgy Flyorov, nhà vật lý Liên Xô." },
            { number: 115, symbol: "Mc", name: "Moscovium", nameVi: "Moscovi", mass: 290, category: "unknown", period: 7, group: 15, electronegativity: null, state: "Rắn", year: "2003", config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³", fact: "Đặt theo tên vùng Moscow, Nga." },
            { number: 116, symbol: "Lv", name: "Livermorium", nameVi: "Livermori", mass: 293, category: "unknown", period: 7, group: 16, electronegativity: null, state: "Rắn", year: "2000", config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴", fact: "Đặt theo tên phòng thí nghiệm Lawrence Livermore." },
            { number: 117, symbol: "Ts", name: "Tennessine", nameVi: "Tennessi", mass: 294, category: "unknown", period: 7, group: 17, electronegativity: null, state: "Rắn", year: "2010", config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵", fact: "Đặt theo tên tiểu bang Tennessee, Mỹ." },
            { number: 118, symbol: "Og", name: "Oganesson", nameVi: "Oganesson", mass: 294, category: "unknown", period: 7, group: 18, electronegativity: null, state: "Rắn", year: "2006", config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶", fact: "Nguyên tố nặng nhất, đặt theo tên Yuri Oganessian." },

            // Lanthanides (58-71)
            { number: 58, symbol: "Ce", name: "Cerium", nameVi: "Xeri", mass: 140.1, category: "lanthanide", period: 6, group: null, electronegativity: 1.12, state: "Rắn", year: "1803", config: "[Xe] 4f¹ 5d¹ 6s²", fact: "Dùng trong kính ô tô tự làm sạch và bật lửa." },
            { number: 59, symbol: "Pr", name: "Praseodymium", nameVi: "Praseođim", mass: 140.9, category: "lanthanide", period: 6, group: null, electronegativity: 1.13, state: "Rắn", year: "1885", config: "[Xe] 4f³ 6s²", fact: "Tạo màu xanh lá cho thủy tinh và gốm sứ." },
            { number: 60, symbol: "Nd", name: "Neodymium", nameVi: "Neođim", mass: 144.2, category: "lanthanide", period: 6, group: null, electronegativity: 1.14, state: "Rắn", year: "1885", config: "[Xe] 4f⁴ 6s²", fact: "Dùng làm nam châm mạnh nhất thế giới." },
            { number: 61, symbol: "Pm", name: "Promethium", nameVi: "Prometi", mass: 145, category: "lanthanide", period: 6, group: null, electronegativity: 1.13, state: "Rắn", year: "1945", config: "[Xe] 4f⁵ 6s²", fact: "Lanthanide phóng xạ duy nhất, dùng trong pin hạt nhân." },
            { number: 62, symbol: "Sm", name: "Samarium", nameVi: "Samari", mass: 150.4, category: "lanthanide", period: 6, group: null, electronegativity: 1.17, state: "Rắn", year: "1879", config: "[Xe] 4f⁶ 6s²", fact: "Dùng trong nam châm SmCo và điều trị ung thư." },
            { number: 63, symbol: "Eu", name: "Europium", nameVi: "Europi", mass: 152.0, category: "lanthanide", period: 6, group: null, electronegativity: 1.2, state: "Rắn", year: "1901", config: "[Xe] 4f⁷ 6s²", fact: "Dùng trong đèn huỳnh quang và tiền giấy chống giả." },
            { number: 64, symbol: "Gd", name: "Gadolinium", nameVi: "Gađolini", mass: 157.3, category: "lanthanide", period: 6, group: null, electronegativity: 1.2, state: "Rắn", year: "1880", config: "[Xe] 4f⁷ 5d¹ 6s²", fact: "Dùng làm chất tương phản MRI trong y tế." },
            { number: 65, symbol: "Tb", name: "Terbium", nameVi: "Terbi", mass: 158.9, category: "lanthanide", period: 6, group: null, electronegativity: 1.2, state: "Rắn", year: "1843", config: "[Xe] 4f⁹ 6s²", fact: "Dùng trong đèn huỳnh quang xanh lá và TV." },
            { number: 66, symbol: "Dy", name: "Dysprosium", nameVi: "Đysprosi", mass: 162.5, category: "lanthanide", period: 6, group: null, electronegativity: 1.22, state: "Rắn", year: "1886", config: "[Xe] 4f¹⁰ 6s²", fact: "Dùng trong động cơ xe điện và tuabin gió." },
            { number: 67, symbol: "Ho", name: "Holmium", nameVi: "Holmi", mass: 164.9, category: "lanthanide", period: 6, group: null, electronegativity: 1.23, state: "Rắn", year: "1878", config: "[Xe] 4f¹¹ 6s²", fact: "Có từ tính mạnh nhất trong các nguyên tố." },
            { number: 68, symbol: "Er", name: "Erbium", nameVi: "Erbi", mass: 167.3, category: "lanthanide", period: 6, group: null, electronegativity: 1.24, state: "Rắn", year: "1843", config: "[Xe] 4f¹² 6s²", fact: "Dùng trong cáp quang và laser y tế." },
            { number: 69, symbol: "Tm", name: "Thulium", nameVi: "Thuli", mass: 168.9, category: "lanthanide", period: 6, group: null, electronegativity: 1.25, state: "Rắn", year: "1879", config: "[Xe] 4f¹³ 6s²", fact: "Lanthanide hiếm nhất, dùng trong laser phẫu thuật." },
            { number: 70, symbol: "Yb", name: "Ytterbium", nameVi: "Ytterbi", mass: 173.0, category: "lanthanide", period: 6, group: null, electronegativity: 1.1, state: "Rắn", year: "1878", config: "[Xe] 4f¹⁴ 6s²", fact: "Dùng trong đồng hồ nguyên tử siêu chính xác." },
            { number: 71, symbol: "Lu", name: "Lutetium", nameVi: "Luteti", mass: 175.0, category: "lanthanide", period: 6, group: null, electronegativity: 1.27, state: "Rắn", year: "1907", config: "[Xe] 4f¹⁴ 5d¹ 6s²", fact: "Dùng trong xúc tác lọc dầu và PET scan." },

            // Actinides (90-103)
            { number: 90, symbol: "Th", name: "Thorium", nameVi: "Thori", mass: 232.0, category: "actinide", period: 7, group: null, electronegativity: 1.3, state: "Rắn", year: "1829", config: "[Rn] 6d² 7s²", fact: "Nhiên liệu hạt nhân tiềm năng, từng dùng trong vỏ đèn gas." },
            { number: 91, symbol: "Pa", name: "Protactinium", nameVi: "Protactini", mass: 231.0, category: "actinide", period: 7, group: null, electronegativity: 1.5, state: "Rắn", year: "1913", config: "[Rn] 5f² 6d¹ 7s²", fact: "Một trong những nguyên tố hiếm nhất và đắt nhất." },
            { number: 92, symbol: "U", name: "Uranium", nameVi: "Urani", mass: 238.0, category: "actinide", period: 7, group: null, electronegativity: 1.38, state: "Rắn", year: "1789", config: "[Rn] 5f³ 6d¹ 7s²", fact: "Nhiên liệu nhà máy điện hạt nhân và vũ khí nguyên tử." },
            { number: 93, symbol: "Np", name: "Neptunium", nameVi: "Neptuni", mass: 237, category: "actinide", period: 7, group: null, electronegativity: 1.36, state: "Rắn", year: "1940", config: "[Rn] 5f⁴ 6d¹ 7s²", fact: "Nguyên tố siêu urani đầu tiên được tổng hợp." },
            { number: 94, symbol: "Pu", name: "Plutonium", nameVi: "Plutoni", mass: 244, category: "actinide", period: 7, group: null, electronegativity: 1.28, state: "Rắn", year: "1940", config: "[Rn] 5f⁶ 7s²", fact: "Dùng trong vũ khí hạt nhân và nguồn điện tàu vũ trụ." },
            { number: 95, symbol: "Am", name: "Americium", nameVi: "Americi", mass: 243, category: "actinide", period: 7, group: null, electronegativity: 1.13, state: "Rắn", year: "1944", config: "[Rn] 5f⁷ 7s²", fact: "Dùng trong đầu dò khói gia đình." },
            { number: 96, symbol: "Cm", name: "Curium", nameVi: "Curi", mass: 247, category: "actinide", period: 7, group: null, electronegativity: 1.28, state: "Rắn", year: "1944", config: "[Rn] 5f⁷ 6d¹ 7s²", fact: "Đặt theo tên vợ chồng Pierre và Marie Curie." },
            { number: 97, symbol: "Bk", name: "Berkelium", nameVi: "Berkeli", mass: 247, category: "actinide", period: 7, group: null, electronegativity: 1.3, state: "Rắn", year: "1949", config: "[Rn] 5f⁹ 7s²", fact: "Đặt theo tên thành phố Berkeley, California." },
            { number: 98, symbol: "Cf", name: "Californium", nameVi: "Californi", mass: 251, category: "actinide", period: 7, group: null, electronegativity: 1.3, state: "Rắn", year: "1950", config: "[Rn] 5f¹⁰ 7s²", fact: "Một gram có giá 27 triệu USD, dùng trong y tế và khai mỏ." },
            { number: 99, symbol: "Es", name: "Einsteinium", nameVi: "Einsteini", mass: 252, category: "actinide", period: 7, group: null, electronegativity: 1.3, state: "Rắn", year: "1952", config: "[Rn] 5f¹¹ 7s²", fact: "Được phát hiện trong bụi phóng xạ của bom H đầu tiên." },
            { number: 100, symbol: "Fm", name: "Fermium", nameVi: "Fermi", mass: 257, category: "actinide", period: 7, group: null, electronegativity: 1.3, state: "Rắn", year: "1952", config: "[Rn] 5f¹² 7s²", fact: "Đặt theo tên Enrico Fermi, cha đẻ lò phản ứng hạt nhân." },
            { number: 101, symbol: "Md", name: "Mendelevium", nameVi: "Menđelevi", mass: 258, category: "actinide", period: 7, group: null, electronegativity: 1.3, state: "Rắn", year: "1955", config: "[Rn] 5f¹³ 7s²", fact: "Đặt theo tên Dmitri Mendeleev, cha đẻ bảng tuần hoàn." },
            { number: 102, symbol: "No", name: "Nobelium", nameVi: "Nobeli", mass: 259, category: "actinide", period: 7, group: null, electronegativity: 1.3, state: "Rắn", year: "1958", config: "[Rn] 5f¹⁴ 7s²", fact: "Đặt theo tên Alfred Nobel, người sáng lập giải Nobel." },
            { number: 103, symbol: "Lr", name: "Lawrencium", nameVi: "Lawrenci", mass: 266, category: "actinide", period: 7, group: null, electronegativity: 1.3, state: "Rắn", year: "1961", config: "[Rn] 5f¹⁴ 7s² 7p¹", fact: "Actinide cuối cùng, đặt theo tên Ernest Lawrence." }
        ];

        // Grid position mapping
        const gridPositions = [
            // Period 1
            { number: 1, row: 1, col: 1 },
            { number: 2, row: 1, col: 18 },
            // Period 2
            { number: 3, row: 2, col: 1 },
            { number: 4, row: 2, col: 2 },
            { number: 5, row: 2, col: 13 },
            { number: 6, row: 2, col: 14 },
            { number: 7, row: 2, col: 15 },
            { number: 8, row: 2, col: 16 },
            { number: 9, row: 2, col: 17 },
            { number: 10, row: 2, col: 18 },
            // Period 3
            { number: 11, row: 3, col: 1 },
            { number: 12, row: 3, col: 2 },
            { number: 13, row: 3, col: 13 },
            { number: 14, row: 3, col: 14 },
            { number: 15, row: 3, col: 15 },
            { number: 16, row: 3, col: 16 },
            { number: 17, row: 3, col: 17 },
            { number: 18, row: 3, col: 18 },
            // Period 4
            { number: 19, row: 4, col: 1 },
            { number: 20, row: 4, col: 2 },
            { number: 21, row: 4, col: 3 },
            { number: 22, row: 4, col: 4 },
            { number: 23, row: 4, col: 5 },
            { number: 24, row: 4, col: 6 },
            { number: 25, row: 4, col: 7 },
            { number: 26, row: 4, col: 8 },
            { number: 27, row: 4, col: 9 },
            { number: 28, row: 4, col: 10 },
            { number: 29, row: 4, col: 11 },
            { number: 30, row: 4, col: 12 },
            { number: 31, row: 4, col: 13 },
            { number: 32, row: 4, col: 14 },
            { number: 33, row: 4, col: 15 },
            { number: 34, row: 4, col: 16 },
            { number: 35, row: 4, col: 17 },
            { number: 36, row: 4, col: 18 },
            // Period 5
            { number: 37, row: 5, col: 1 },
            { number: 38, row: 5, col: 2 },
            { number: 39, row: 5, col: 3 },
            { number: 40, row: 5, col: 4 },
            { number: 41, row: 5, col: 5 },
            { number: 42, row: 5, col: 6 },
            { number: 43, row: 5, col: 7 },
            { number: 44, row: 5, col: 8 },
            { number: 45, row: 5, col: 9 },
            { number: 46, row: 5, col: 10 },
            { number: 47, row: 5, col: 11 },
            { number: 48, row: 5, col: 12 },
            { number: 49, row: 5, col: 13 },
            { number: 50, row: 5, col: 14 },
            { number: 51, row: 5, col: 15 },
            { number: 52, row: 5, col: 16 },
            { number: 53, row: 5, col: 17 },
            { number: 54, row: 5, col: 18 },
            // Period 6
            { number: 55, row: 6, col: 1 },
            { number: 56, row: 6, col: 2 },
            { number: 57, row: 6, col: 3 }, // La placeholder
            { number: 72, row: 6, col: 4 },
            { number: 73, row: 6, col: 5 },
            { number: 74, row: 6, col: 6 },
            { number: 75, row: 6, col: 7 },
            { number: 76, row: 6, col: 8 },
            { number: 77, row: 6, col: 9 },
            { number: 78, row: 6, col: 10 },
            { number: 79, row: 6, col: 11 },
            { number: 80, row: 6, col: 12 },
            { number: 81, row: 6, col: 13 },
            { number: 82, row: 6, col: 14 },
            { number: 83, row: 6, col: 15 },
            { number: 84, row: 6, col: 16 },
            { number: 85, row: 6, col: 17 },
            { number: 86, row: 6, col: 18 },
            // Period 7
            { number: 87, row: 7, col: 1 },
            { number: 88, row: 7, col: 2 },
            { number: 89, row: 7, col: 3 }, // Ac placeholder
            { number: 104, row: 7, col: 4 },
            { number: 105, row: 7, col: 5 },
            { number: 106, row: 7, col: 6 },
            { number: 107, row: 7, col: 7 },
            { number: 108, row: 7, col: 8 },
            { number: 109, row: 7, col: 9 },
            { number: 110, row: 7, col: 10 },
            { number: 111, row: 7, col: 11 },
            { number: 112, row: 7, col: 12 },
            { number: 113, row: 7, col: 13 },
            { number: 114, row: 7, col: 14 },
            { number: 115, row: 7, col: 15 },
            { number: 116, row: 7, col: 16 },
            { number: 117, row: 7, col: 17 },
            { number: 118, row: 7, col: 18 },
            // Lanthanides (row 9)
            { number: 58, row: 9, col: 4 },
            { number: 59, row: 9, col: 5 },
            { number: 60, row: 9, col: 6 },
            { number: 61, row: 9, col: 7 },
            { number: 62, row: 9, col: 8 },
            { number: 63, row: 9, col: 9 },
            { number: 64, row: 9, col: 10 },
            { number: 65, row: 9, col: 11 },
            { number: 66, row: 9, col: 12 },
            { number: 67, row: 9, col: 13 },
            { number: 68, row: 9, col: 14 },
            { number: 69, row: 9, col: 15 },
            { number: 70, row: 9, col: 16 },
            { number: 71, row: 9, col: 17 },
            // Actinides (row 10)
            { number: 90, row: 10, col: 4 },
            { number: 91, row: 10, col: 5 },
            { number: 92, row: 10, col: 6 },
            { number: 93, row: 10, col: 7 },
            { number: 94, row: 10, col: 8 },
            { number: 95, row: 10, col: 9 },
            { number: 96, row: 10, col: 10 },
            { number: 97, row: 10, col: 11 },
            { number: 98, row: 10, col: 12 },
            { number: 99, row: 10, col: 13 },
            { number: 100, row: 10, col: 14 },
            { number: 101, row: 10, col: 15 },
            { number: 102, row: 10, col: 16 },
            { number: 103, row: 10, col: 17 }
        ];

        // Category names in Vietnamese
        const categoryNames = {
            'alkali': 'Kim loại kiềm',
            'alkaline': 'Kim loại kiềm thổ',
            'transition': 'Kim loại chuyển tiếp',
            'post-transition': 'Kim loại yếu',
            'metalloid': 'Á kim',
            'nonmetal': 'Phi kim',
            'halogen': 'Halogen',
            'noble': 'Khí hiếm',
            'lanthanide': 'Lantanit',
            'actinide': 'Actinit',
            'unknown': 'Chưa xác định'
        };

        // IPA Pronunciations for all elements
        const elementPronunciations = {
            "Hydrogen": { ipa: "/ˈhaɪdrədʒən/", speak: "Hydrogen" },
            "Helium": { ipa: "/ˈhiːliəm/", speak: "Helium" },
            "Lithium": { ipa: "/ˈlɪθiəm/", speak: "Lithium" },
            "Beryllium": { ipa: "/bəˈrɪliəm/", speak: "Beryllium" },
            "Boron": { ipa: "/ˈbɔːrɒn/", speak: "Boron" },
            "Carbon": { ipa: "/ˈkɑːbən/", speak: "Carbon" },
            "Nitrogen": { ipa: "/ˈnaɪtrədʒən/", speak: "Nitrogen" },
            "Oxygen": { ipa: "/ˈɒksɪdʒən/", speak: "Oxygen" },
            "Fluorine": { ipa: "/ˈflʊəriːn/", speak: "Fluorine" },
            "Neon": { ipa: "/ˈniːɒn/", speak: "Neon" },
            "Sodium": { ipa: "/ˈsəʊdiəm/", speak: "Sodium" },
            "Magnesium": { ipa: "/mæɡˈniːziəm/", speak: "Magnesium" },
            "Aluminium": { ipa: "/ˌæljʊˈmɪniəm/", speak: "Aluminium" },
            "Silicon": { ipa: "/ˈsɪlɪkən/", speak: "Silicon" },
            "Phosphorus": { ipa: "/ˈfɒsfərəs/", speak: "Phosphorus" },
            "Sulfur": { ipa: "/ˈsʌlfər/", speak: "Sulfur" },
            "Chlorine": { ipa: "/ˈklɔːriːn/", speak: "Chlorine" },
            "Argon": { ipa: "/ˈɑːɡɒn/", speak: "Argon" },
            "Potassium": { ipa: "/pəˈtæsiəm/", speak: "Potassium" },
            "Calcium": { ipa: "/ˈkælsiəm/", speak: "Calcium" },
            "Scandium": { ipa: "/ˈskændiəm/", speak: "Scandium" },
            "Titanium": { ipa: "/taɪˈteɪniəm/", speak: "Titanium" },
            "Vanadium": { ipa: "/vəˈneɪdiəm/", speak: "Vanadium" },
            "Chromium": { ipa: "/ˈkrəʊmiəm/", speak: "Chromium" },
            "Manganese": { ipa: "/ˈmæŋɡəniːz/", speak: "Manganese" },
            "Iron": { ipa: "/ˈaɪən/", speak: "Iron" },
            "Cobalt": { ipa: "/ˈkəʊbɔːlt/", speak: "Cobalt" },
            "Nickel": { ipa: "/ˈnɪkəl/", speak: "Nickel" },
            "Copper": { ipa: "/ˈkɒpər/", speak: "Copper" },
            "Zinc": { ipa: "/zɪŋk/", speak: "Zinc" },
            "Gallium": { ipa: "/ˈɡæliəm/", speak: "Gallium" },
            "Germanium": { ipa: "/dʒɜːˈmeɪniəm/", speak: "Germanium" },
            "Arsenic": { ipa: "/ˈɑːsnɪk/", speak: "Arsenic" },
            "Selenium": { ipa: "/sɪˈliːniəm/", speak: "Selenium" },
            "Bromine": { ipa: "/ˈbrəʊmiːn/", speak: "Bromine" },
            "Krypton": { ipa: "/ˈkrɪptɒn/", speak: "Krypton" },
            "Rubidium": { ipa: "/ruːˈbɪdiəm/", speak: "Rubidium" },
            "Strontium": { ipa: "/ˈstrɒntiəm/", speak: "Strontium" },
            "Yttrium": { ipa: "/ˈɪtriəm/", speak: "Yttrium" },
            "Zirconium": { ipa: "/zɜːˈkəʊniəm/", speak: "Zirconium" },
            "Niobium": { ipa: "/naɪˈəʊbiəm/", speak: "Niobium" },
            "Molybdenum": { ipa: "/məˈlɪbdənəm/", speak: "Molybdenum" },
            "Technetium": { ipa: "/tekˈniːʃiəm/", speak: "Technetium" },
            "Ruthenium": { ipa: "/ruːˈθiːniəm/", speak: "Ruthenium" },
            "Rhodium": { ipa: "/ˈrəʊdiəm/", speak: "Rhodium" },
            "Palladium": { ipa: "/pəˈleɪdiəm/", speak: "Palladium" },
            "Silver": { ipa: "/ˈsɪlvər/", speak: "Silver" },
            "Cadmium": { ipa: "/ˈkædmiəm/", speak: "Cadmium" },
            "Indium": { ipa: "/ˈɪndiəm/", speak: "Indium" },
            "Tin": { ipa: "/tɪn/", speak: "Tin" },
            "Antimony": { ipa: "/ˈæntɪməni/", speak: "Antimony" },
            "Tellurium": { ipa: "/tɪˈljʊəriəm/", speak: "Tellurium" },
            "Iodine": { ipa: "/ˈaɪədiːn/", speak: "Iodine" },
            "Xenon": { ipa: "/ˈziːnɒn/", speak: "Xenon" },
            "Cesium": { ipa: "/ˈsiːziəm/", speak: "Cesium" },
            "Barium": { ipa: "/ˈbeəriəm/", speak: "Barium" },
            "Lanthanum": { ipa: "/ˈlænθənəm/", speak: "Lanthanum" },
            "Cerium": { ipa: "/ˈsɪəriəm/", speak: "Cerium" },
            "Praseodymium": { ipa: "/ˌpreɪziəʊˈdɪmiəm/", speak: "Praseodymium" },
            "Neodymium": { ipa: "/ˌniːəʊˈdɪmiəm/", speak: "Neodymium" },
            "Promethium": { ipa: "/prəˈmiːθiəm/", speak: "Promethium" },
            "Samarium": { ipa: "/səˈmeəriəm/", speak: "Samarium" },
            "Europium": { ipa: "/jʊˈrəʊpiəm/", speak: "Europium" },
            "Gadolinium": { ipa: "/ˌɡædəˈlɪniəm/", speak: "Gadolinium" },
            "Terbium": { ipa: "/ˈtɜːbiəm/", speak: "Terbium" },
            "Dysprosium": { ipa: "/dɪsˈprəʊziəm/", speak: "Dysprosium" },
            "Holmium": { ipa: "/ˈhəʊlmiəm/", speak: "Holmium" },
            "Erbium": { ipa: "/ˈɜːbiəm/", speak: "Erbium" },
            "Thulium": { ipa: "/ˈθjuːliəm/", speak: "Thulium" },
            "Ytterbium": { ipa: "/ɪˈtɜːbiəm/", speak: "Ytterbium" },
            "Lutetium": { ipa: "/luːˈtiːʃiəm/", speak: "Lutetium" },
            "Hafnium": { ipa: "/ˈhæfniəm/", speak: "Hafnium" },
            "Tantalum": { ipa: "/ˈtæntələm/", speak: "Tantalum" },
            "Tungsten": { ipa: "/ˈtʌŋstən/", speak: "Tungsten" },
            "Rhenium": { ipa: "/ˈriːniəm/", speak: "Rhenium" },
            "Osmium": { ipa: "/ˈɒzmiəm/", speak: "Osmium" },
            "Iridium": { ipa: "/ɪˈrɪdiəm/", speak: "Iridium" },
            "Platinum": { ipa: "/ˈplætɪnəm/", speak: "Platinum" },
            "Gold": { ipa: "/ɡəʊld/", speak: "Gold" },
            "Mercury": { ipa: "/ˈmɜːkjʊri/", speak: "Mercury" },
            "Thallium": { ipa: "/ˈθæliəm/", speak: "Thallium" },
            "Lead": { ipa: "/led/", speak: "Lead" },
            "Bismuth": { ipa: "/ˈbɪzməθ/", speak: "Bismuth" },
            "Polonium": { ipa: "/pəˈləʊniəm/", speak: "Polonium" },
            "Astatine": { ipa: "/ˈæstətiːn/", speak: "Astatine" },
            "Radon": { ipa: "/ˈreɪdɒn/", speak: "Radon" },
            "Francium": { ipa: "/ˈfrænsiəm/", speak: "Francium" },
            "Radium": { ipa: "/ˈreɪdiəm/", speak: "Radium" },
            "Actinium": { ipa: "/ækˈtɪniəm/", speak: "Actinium" },
            "Thorium": { ipa: "/ˈθɔːriəm/", speak: "Thorium" },
            "Protactinium": { ipa: "/ˌprəʊtækˈtɪniəm/", speak: "Protactinium" },
            "Uranium": { ipa: "/jʊˈreɪniəm/", speak: "Uranium" },
            "Neptunium": { ipa: "/nepˈtjuːniəm/", speak: "Neptunium" },
            "Plutonium": { ipa: "/pluːˈtəʊniəm/", speak: "Plutonium" },
            "Americium": { ipa: "/ˌæməˈrɪsiəm/", speak: "Americium" },
            "Curium": { ipa: "/ˈkjʊəriəm/", speak: "Curium" },
            "Berkelium": { ipa: "/bɜːˈkiːliəm/", speak: "Berkelium" },
            "Californium": { ipa: "/ˌkælɪˈfɔːniəm/", speak: "Californium" },
            "Einsteinium": { ipa: "/aɪnˈstaɪniəm/", speak: "Einsteinium" },
            "Fermium": { ipa: "/ˈfɜːmiəm/", speak: "Fermium" },
            "Mendelevium": { ipa: "/ˌmendəˈliːviəm/", speak: "Mendelevium" },
            "Nobelium": { ipa: "/nəʊˈbiːliəm/", speak: "Nobelium" },
            "Lawrencium": { ipa: "/lɔːˈrensiəm/", speak: "Lawrencium" },
            "Rutherfordium": { ipa: "/ˌrʌðəˈfɔːdiəm/", speak: "Rutherfordium" },
            "Dubnium": { ipa: "/ˈdʌbniəm/", speak: "Dubnium" },
            "Seaborgium": { ipa: "/siːˈbɔːɡiəm/", speak: "Seaborgium" },
            "Bohrium": { ipa: "/ˈbɔːriəm/", speak: "Bohrium" },
            "Hassium": { ipa: "/ˈhæsiəm/", speak: "Hassium" },
            "Meitnerium": { ipa: "/maɪtˈnɪəriəm/", speak: "Meitnerium" },
            "Darmstadtium": { ipa: "/dɑːmˈʃtætiəm/", speak: "Darmstadtium" },
            "Roentgenium": { ipa: "/rɒntˈɡiːniəm/", speak: "Roentgenium" },
            "Copernicium": { ipa: "/ˌkəʊpərˈnɪsiəm/", speak: "Copernicium" },
            "Nihonium": { ipa: "/nɪˈhəʊniəm/", speak: "Nihonium" },
            "Flerovium": { ipa: "/flɪˈrɒviəm/", speak: "Flerovium" },
            "Moscovium": { ipa: "/mɒsˈkəʊviəm/", speak: "Moscovium" },
            "Livermorium": { ipa: "/ˌlɪvərˈmɔːriəm/", speak: "Livermorium" },
            "Tennessine": { ipa: "/ˈtenəsiːn/", speak: "Tennessine" },
            "Oganesson": { ipa: "/ˌɒɡəˈnesɒn/", speak: "Oganesson" },
            // Vietnamese names mapping to English for pronunciation
            "Hydro": { ipa: "/ˈhaɪdrədʒən/", speak: "Hydrogen" },
            "Heli": { ipa: "/ˈhiːliəm/", speak: "Helium" },
            "Liti": { ipa: "/ˈlɪθiəm/", speak: "Lithium" },
            "Berili": { ipa: "/bəˈrɪliəm/", speak: "Beryllium" },
            "Bo": { ipa: "/ˈbɔːrɒn/", speak: "Boron" },
            "Cacbon": { ipa: "/ˈkɑːbən/", speak: "Carbon" },
            "Nitơ": { ipa: "/ˈnaɪtrədʒən/", speak: "Nitrogen" },
            "Oxi": { ipa: "/ˈɒksɪdʒən/", speak: "Oxygen" },
            "Flo": { ipa: "/ˈflʊəriːn/", speak: "Fluorine" },
            "Natri": { ipa: "/ˈsəʊdiəm/", speak: "Sodium" },
            "Magiê": { ipa: "/mæɡˈniːziəm/", speak: "Magnesium" },
            "Nhôm": { ipa: "/ˌæljʊˈmɪniəm/", speak: "Aluminium" },
            "Silic": { ipa: "/ˈsɪlɪkən/", speak: "Silicon" },
            "Photpho": { ipa: "/ˈfɒsfərəs/", speak: "Phosphorus" },
            "Lưu huỳnh": { ipa: "/ˈsʌlfər/", speak: "Sulfur" },
            "Clo": { ipa: "/ˈklɔːriːn/", speak: "Chlorine" },
            "Kali": { ipa: "/pəˈtæsiəm/", speak: "Potassium" },
            "Canxi": { ipa: "/ˈkælsiəm/", speak: "Calcium" },
            "Scandi": { ipa: "/ˈskændiəm/", speak: "Scandium" },
            "Titan": { ipa: "/taɪˈteɪniəm/", speak: "Titanium" },
            "Vanadi": { ipa: "/vəˈneɪdiəm/", speak: "Vanadium" },
            "Crom": { ipa: "/ˈkrəʊmiəm/", speak: "Chromium" },
            "Mangan": { ipa: "/ˈmæŋɡəniːz/", speak: "Manganese" },
            "Sắt": { ipa: "/ˈaɪən/", speak: "Iron" },
            "Coban": { ipa: "/ˈkəʊbɔːlt/", speak: "Cobalt" },
            "Niken": { ipa: "/ˈnɪkəl/", speak: "Nickel" },
            "Đồng": { ipa: "/ˈkɒpər/", speak: "Copper" },
            "Kẽm": { ipa: "/zɪŋk/", speak: "Zinc" },
            "Gali": { ipa: "/ˈɡæliəm/", speak: "Gallium" },
            "Gecmani": { ipa: "/dʒɜːˈmeɪniəm/", speak: "Germanium" },
            "Asen": { ipa: "/ˈɑːsnɪk/", speak: "Arsenic" },
            "Selen": { ipa: "/sɪˈliːniəm/", speak: "Selenium" },
            "Brom": { ipa: "/ˈbrəʊmiːn/", speak: "Bromine" },
            "Kripton": { ipa: "/ˈkrɪptɒn/", speak: "Krypton" },
            "Rubidi": { ipa: "/ruːˈbɪdiəm/", speak: "Rubidium" },
            "Stronti": { ipa: "/ˈstrɒntiəm/", speak: "Strontium" },
            "Ytri": { ipa: "/ˈɪtriəm/", speak: "Yttrium" },
            "Zirconi": { ipa: "/zɜːˈkəʊniəm/", speak: "Zirconium" },
            "Niobi": { ipa: "/naɪˈəʊbiəm/", speak: "Niobium" },
            "Molypđen": { ipa: "/məˈlɪbdənəm/", speak: "Molybdenum" },
            "Tecneti": { ipa: "/tekˈniːʃiəm/", speak: "Technetium" },
            "Ruteni": { ipa: "/ruːˈθiːniəm/", speak: "Ruthenium" },
            "Rođi": { ipa: "/ˈrəʊdiəm/", speak: "Rhodium" },
            "Palađi": { ipa: "/pəˈleɪdiəm/", speak: "Palladium" },
            "Bạc": { ipa: "/ˈsɪlvər/", speak: "Silver" },
            "Cađimi": { ipa: "/ˈkædmiəm/", speak: "Cadmium" },
            "Inđi": { ipa: "/ˈɪndiəm/", speak: "Indium" },
            "Thiếc": { ipa: "/tɪn/", speak: "Tin" },
            "Antimon": { ipa: "/ˈæntɪməni/", speak: "Antimony" },
            "Telu": { ipa: "/tɪˈljʊəriəm/", speak: "Tellurium" },
            "Iot": { ipa: "/ˈaɪədiːn/", speak: "Iodine" },
            "Xesi": { ipa: "/ˈsiːziəm/", speak: "Cesium" },
            "Bari": { ipa: "/ˈbeəriəm/", speak: "Barium" },
            "Lantan": { ipa: "/ˈlænθənəm/", speak: "Lanthanum" },
            "Xeri": { ipa: "/ˈsɪəriəm/", speak: "Cerium" },
            "Praseođim": { ipa: "/ˌpreɪziəʊˈdɪmiəm/", speak: "Praseodymium" },
            "Neođim": { ipa: "/ˌniːəʊˈdɪmiəm/", speak: "Neodymium" },
            "Prometi": { ipa: "/prəˈmiːθiəm/", speak: "Promethium" },
            "Samari": { ipa: "/səˈmeəriəm/", speak: "Samarium" },
            "Europi": { ipa: "/jʊˈrəʊpiəm/", speak: "Europium" },
            "Gađolini": { ipa: "/ˌɡædəˈlɪniəm/", speak: "Gadolinium" },
            "Terbi": { ipa: "/ˈtɜːbiəm/", speak: "Terbium" },
            "Đysprosi": { ipa: "/dɪsˈprəʊziəm/", speak: "Dysprosium" },
            "Holmi": { ipa: "/ˈhəʊlmiəm/", speak: "Holmium" },
            "Erbi": { ipa: "/ˈɜːbiəm/", speak: "Erbium" },
            "Thuli": { ipa: "/ˈθjuːliəm/", speak: "Thulium" },
            "Ytterbi": { ipa: "/ɪˈtɜːbiəm/", speak: "Ytterbium" },
            "Luteti": { ipa: "/luːˈtiːʃiəm/", speak: "Lutetium" },
            "Hafni": { ipa: "/ˈhæfniəm/", speak: "Hafnium" },
            "Tantan": { ipa: "/ˈtæntələm/", speak: "Tantalum" },
            "Vonfram": { ipa: "/ˈtʌŋstən/", speak: "Tungsten" },
            "Reni": { ipa: "/ˈriːniəm/", speak: "Rhenium" },
            "Osmi": { ipa: "/ˈɒzmiəm/", speak: "Osmium" },
            "Iriđi": { ipa: "/ɪˈrɪdiəm/", speak: "Iridium" },
            "Platin": { ipa: "/ˈplætɪnəm/", speak: "Platinum" },
            "Vàng": { ipa: "/ɡəʊld/", speak: "Gold" },
            "Thủy ngân": { ipa: "/ˈmɜːkjʊri/", speak: "Mercury" },
            "Tali": { ipa: "/ˈθæliəm/", speak: "Thallium" },
            "Chì": { ipa: "/led/", speak: "Lead" },
            "Bitmut": { ipa: "/ˈbɪzməθ/", speak: "Bismuth" },
            "Poloni": { ipa: "/pəˈləʊniəm/", speak: "Polonium" },
            "Atatin": { ipa: "/ˈæstətiːn/", speak: "Astatine" },
            "Rađon": { ipa: "/ˈreɪdɒn/", speak: "Radon" },
            "Franxi": { ipa: "/ˈfrænsiəm/", speak: "Francium" },
            "Rađi": { ipa: "/ˈreɪdiəm/", speak: "Radium" },
            "Actini": { ipa: "/ækˈtɪniəm/", speak: "Actinium" },
            "Thori": { ipa: "/ˈθɔːriəm/", speak: "Thorium" },
            "Protactini": { ipa: "/ˌprəʊtækˈtɪniəm/", speak: "Protactinium" },
            "Urani": { ipa: "/jʊˈreɪniəm/", speak: "Uranium" },
            "Neptuni": { ipa: "/nepˈtjuːniəm/", speak: "Neptunium" },
            "Plutoni": { ipa: "/pluːˈtəʊniəm/", speak: "Plutonium" },
            "Americi": { ipa: "/ˌæməˈrɪsiəm/", speak: "Americium" },
            "Curi": { ipa: "/ˈkjʊəriəm/", speak: "Curium" },
            "Berkeli": { ipa: "/bɜːˈkiːliəm/", speak: "Berkelium" },
            "Californi": { ipa: "/ˌkælɪˈfɔːniəm/", speak: "Californium" },
            "Einsteini": { ipa: "/aɪnˈstaɪniəm/", speak: "Einsteinium" },
            "Fermi": { ipa: "/ˈfɜːmiəm/", speak: "Fermium" },
            "Menđelevi": { ipa: "/ˌmendəˈliːviəm/", speak: "Mendelevium" },
            "Nobeli": { ipa: "/nəʊˈbiːliəm/", speak: "Nobelium" },
            "Lawrenci": { ipa: "/lɔːˈrensiəm/", speak: "Lawrencium" },
            "Rutherforđi": { ipa: "/ˌrʌðəˈfɔːdiəm/", speak: "Rutherfordium" },
            "Dubni": { ipa: "/ˈdʌbniəm/", speak: "Dubnium" },
            "Seaborgi": { ipa: "/siːˈbɔːɡiəm/", speak: "Seaborgium" },
            "Bohri": { ipa: "/ˈbɔːriəm/", speak: "Bohrium" },
            "Hassi": { ipa: "/ˈhæsiəm/", speak: "Hassium" },
            "Meitneri": { ipa: "/maɪtˈnɪəriəm/", speak: "Meitnerium" },
            "Darmstadti": { ipa: "/dɑːmˈʃtætiəm/", speak: "Darmstadtium" },
            "Roentgeni": { ipa: "/rɒntˈɡiːniəm/", speak: "Roentgenium" },
            "Copernici": { ipa: "/ˌkəʊpərˈnɪsiəm/", speak: "Copernicium" },
            "Nihoni": { ipa: "/nɪˈhəʊniəm/", speak: "Nihonium" },
            "Flerovi": { ipa: "/flɪˈrɒviəm/", speak: "Flerovium" },
            "Moscovi": { ipa: "/mɒsˈkəʊviəm/", speak: "Moscovium" },
            "Livermori": { ipa: "/ˌlɪvərˈmɔːriəm/", speak: "Livermorium" },
            "Tennessi": { ipa: "/ˈtenəsiːn/", speak: "Tennessine" }
        };
